### PR TITLE
Fix #79

### LINKED ISSUE #79: "Add to Home Screen" feature doesn't work

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by gauntface** [comment]
Thanks for the PR I'm wondering if just adding '?homescreen=1' rather than ./?homescreen=1

**Comment by FluorescentHallucinogen** [comment]
No, `"?homescreen=1"` value of `"start_url"` key points to https://gauntface.github.io/simple-push-demo/manifest.json?homescreen=1 URL. (Because `""` (empty) value points to https://gauntface.github.io/simple-push-demo/manifest.json URL).

`"./?homescreen=1"` points to https://gauntface.github.io/simple-push-demo/?homescreen=1 – this is what need.

**Comment by jasan-s** [comment]
I visited the  https://gauntface.github.io/simple-push-demo/ more than twice with more than 5 minutes apart yet i did not receive a banner to add to homescreen

**Comment by gauntface** [comment]
It takes weeks for a user to get the banner.

**Comment by jasan-s** [comment]
weeks? according to [this]( https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/web-app-install-banners?hl=en)
the requirements are met. Has the requirements changed?

`

**Comment by FluorescentHallucinogen** [comment]
@jasan-s, do you use mobile or desktop Chrome?

**Comment by FluorescentHallucinogen** [comment]
The heuristics described in https://goo.gl/pxyp5a aren't guaranteed to trigger it.

Just checked on Chrome for Android, all work like a charm!

"Add to Home Screen" feature is disabled by default on Chrome for desktop. You can use `chrome://flags/#enable-add-to-shelf` to enable it. You can also disable the visit frequency check using `chrome://flags/#bypass-app-banner-engagement-checks` on both, mobile and desktop Chrome.

**Comment by jasan-s** [comment]
i am using chrome on mobile . It triggered after I  closed the tab and entered the url again. i had tried by keeping the tab open in chrome open and just going back to the site and using it.

**Pull request merged**
