### PR TITLE
feat(https): enforce HTTPS

### PR DESCRIPTION
**Pull request by domfarolino**
This may be useful so that people are always hitting HTTPS version of site and never see the "You Need to be HTTPs" warning message

### CODE REVIEW

**Comment by gauntface** [comment]
Would you be open to moving this into the code that currently shows the HTTPS message?

https://github.com/gauntface/simple-push-demo/blob/d053625b8dc98096482bbb63d8cc557be674ad92/src/scripts/main.js#L12

**Comment by domfarolino** [comment]
@gauntface Yeah that makes more sense, I'll get on that a bit later today.

**Comment by gauntface** [comment]
@domfarolino thank you, appreciate :). Not sure why I didn't do that at first - probably rebelling against github not enforcing HTTPS :P

**Comment by gauntface** [comment]
Thank you again for this.

**Comment by domfarolino** [comment]
@gauntface Yep!

**Pull request merged**
