### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@gauntface, PTAL. ;)

**Comment by gauntface** [comment]
This looks great, thank you.

Do you think the header bar at the top of the page should have a different color to match the logo + logo?

**Comment by FluorescentHallucinogen** [comment]
> to match the logo + logo

What you mean?

**Comment by FluorescentHallucinogen** [comment]
I think all is ok. ;)

screenshot

**Comment by gauntface** [comment]
Sorry you are right, looks good - one last remaining question, where is the logo from? Is it ok to use in this open source project with the Apache 2.0 license?

Promise I'll take the PR after that :P

**Comment by FluorescentHallucinogen** [comment]
The logo have been generated using https://github.com/Maddoc42/Android-Material-Icon-Generator

Android Material Icon Generator License
================================

Icons generated with the Android Material Icon Generator come with the Creative Common
Attribution 4.0 International License (CC-BY 4.0). You are free to change,
combine and sell any of the icons as you please. Attribution would be great,
but is not strictly required.

This text only applies to the icons (.zip file) you download from the icon
generator. The software behind the generator has its own license
(https://www.apache.org/licenses/LICENSE-2.0). See the GitHub repository for
details (https://github.com/Maddoc42/Android-Material-Icon-Generator).



Google Material Icons License
=============================

(Copied from https://github.com/google/material-design-icons)
We have made these icons available for you to incorporate them into your
products under the Creative Common Attribution 4.0 International License (CC-BY
4.0, https://creativecommons.org/licenses/by/4.0/). Feel free to remix and
re-share these icons and documentation in your products.  We'd love attribution
in your app's *about* screen, but it's not required.  The only thing we ask is
that you not re-sell the icons themselves.

**Comment by koko654321** [comment]
I dont even know u? why are u fucking up my computers and even bragging about it? I have been depressed and crying for month, but now when i found traces of u on my comp i feel so angry that a ugly little geek can ruin my life like that, so i want to come after u and do unspeakable things with u. Are u mentally desturbed because u where bullied at school and the only person ur strong enough to hit back is a deadly sick old lady with the most miserable life u can imagine? I dont even have money to buy myself a new laptop or phone and im just sitting in this institution waiting to die. WHY?

**Pull request merged**
